add_newline = false
format = """
$directory\
$git_branch\
$jobs\
$fill
$character\
$line_break\
"""
right_format = """
$cmd_duration\
$time\
"""

[directory]
disabled = false
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "bold #cdd6f4"
truncation_length = 5

[fill]
disabled = false
symbol = "󰁆 "
style = "bold #9399b2"

[git_branch]
symbol = " "

[lua]
symbol = " "
format = "[$symbol($version)]($style) "

[character]
format = "$symbol "
success_symbol = "[](bold #a6e3a1) "
error_symbol = "[](bold #f38ba8) "
vimcmd_symbol = "[ ](bold #f2cdcd) "
vimcmd_visual_symbol = "[ ](bold #b4befe) "

[time]
disabled = false
format = "[󰥔 $time](bold #cba7f7) "
time_format = "%H:%M %p"
use_12hr = true

[cmd_duration]
disabled = false
min_time = 3
format = "[󰔚 $duration](bold #f9e2af) "

[line_break]
disabled = false
